CC := gcc

objetos = main.c func1.c func2.c func3.c

all: main.o func1.o func2.o func3.o
	gcc -o main $(objetos)	

main.o: main.c func1.h func2.h func3.h
func1.o: func1.c
func2.o: func2.c func1.h
func3.o: func3.c func1.h func2.h

run:
	./main
